- name: 复制 cni-plugins 压缩文件
  copy:
      src: /{{ local_dir }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz
      dest: /{{ remote_dir }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz

- name: 复制 flannel 压缩文件
  copy: 
      src: /{{ local_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz
      dest: /{{ remote_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz

- name: 新建 cni 目录
  file:
      path: "{{ cni_dir }}"
      state: directory
- name: 解压 cni-plugins 文件
  unarchive: 
           src: /{{ remote_dir }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz
           dest: "{{ cni_dir }}"
           copy: no

- name: 新建 cni 配置目录
  file:
      path: "{{ cni_conflist_dir }}"
      state: directory
- name: 复制 flannel-cni 配置文件
  template:
          src: 10-flannel.conflist.j2
          dest: "{{ cni_conflist_dir }}/10-flannel.conflist"

- name: 解压 flannel 文件
  unarchive: 
           src: /{{ remote_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz 
           dest: /{{ remote_dir }}
           copy: no

- name: 复制 flanneld
  command: cp /{{ remote_dir }}/flanneld  {{ bin_dir }}
- name: 新建目录
  file: 
      path: /usr/libexec/flannel/
      state: directory

- name: 复制 mk-docker-opts.sh
  command: cp /{{ remote_dir }}/mk-docker-opts.sh  /usr/libexec/flannel/
- name: 复制 flannel 启动项
  template:
          src: flanneld.service.j2
          dest: /usr/lib/systemd/system/flanneld.service

- name: 复制 flanneld-start
  template:
          src: flanneld-start.j2
          dest: "{{ bin_dir }}/flanneld-start"
          mode: 744

- name: 复制 flannel 配置文件
  template:
          src: flanneld.j2
          dest: /etc/sysconfig/flanneld
          
- name: 重载
  command: systemctl daemon-reload

- name: 启动 flannel
  service:
         name: flanneld
         state: started
         enabled: yes

- name: 重启 containerd
  service:
         name: containerd
         state: restarted
